### ISSUE TITLE
Can't implement v1.0.1 via gradle

### ISSUE THREAD

**Issue by acmeuno** [stfalcon-studio/StfalconImageViewer#76]
Github URL has change so Jitpack goes now under 	        **implementation 'com.github.stfalcon-studio:StfalconImageViewer:v1.0.1'**

Anyway "Could not find com.github.stfalcon-studio:StfalconImageViewer:v1.0.1"

**Comment by naltynbekkz** [comment]
I think you just need to remove the 'v' in the dependency: use
implementation 'com.github.stfalcon-studio:StfalconImageViewer:1.0.1' instead of
implementation 'com.github.stfalcon-studio:StfalconImageViewer:v1.0.1'

**Comment by apm-christian-dziuba** [comment]
The readme.md should be fixed. The v bevore the numbers is wrong. 

`And then add the dependency to the module build.gradle file:

implementation 'com.github.stfalcon:stfalcon-imageviewer:v1.0.1'`

**Comment by SabinaHaselboeck** [comment]
Additionally, if you aren't able to build your project, enable the gradle offline mode and sync your project!

**Comment by softsan** [comment]
i am having the same issue.. event without "v" so any ideas?

**Comment by Orlandroid** [comment]
i remove the v in the librery and i am still getting the sam error
